server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/5003?characterEncoding=UTF8&autoConnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 11229988
    driver-class-name: com.mysql.cj.jdbc.Driver
